blank_issues_enabled: false
contact_links:
  - name: Questions & General Discussion
    url: https://github.com/OrionArch/GlowSchedule/discussions
    about: Ask questions and discuss ideas with the community.
